version: '3.4'

services:
  dis-cloud-1:
    image: dis-cloud
    environment:
      - HTTP_PORT=80

  dis-cloud-2:
    image: dis-cloud
    environment:
      - HTTP_PORT=80

  dis-cloud-3:
    image: dis-cloud
    environment:
      - HTTP_PORT=80

  loadbalancer:
    image: loadbalancer
    environment:
      - HTTP_PORT=8000
    ports:
      - "8000:8000"