version: '3.4'

services:
  dis-cloud-1:
    image: dis-cloud
    environment:
      - HTTP_PORT=8080
    ports:
      - "8080:8080"

  dis-cloud-2:
    image: dis-cloud
    environment:
      - HTTP_PORT=8081
    ports:
      - "8081:8081"
      
  dis-cloud-3:
    image: dis-cloud
    environment:
      - HTTP_PORT=8082
    ports:
      - "8082:8082"